### ISSUE TITLE
Not working on GL553VD-DS71

### ISSUE THREAD

**Issue by physicien** [flozz/asus-keyboard-backlight#1]
I just tried to install it, and the driver does not seem to work on my ASUS GL553VD. The distro is Kali Linux 2017.1.
These two files are missing:
```
MAX_BRIGHTNESS_FILE = "/sys/devices/platform/asus_laptop/leds/asus::kbd_backlight/max_brightness"
BRIGHTNESS_FILE = "/sys/devices/platform/asus_laptop/leds/asus::kbd_backlight/brightness"
```

**Comment by flozz** [comment]
Hello,

* Does the `/sys/devices/platform/asus_laptop/` folder exists?
* If not, is there an  `asus-wmi` (or a one with a similar name) in `/sys/devices/platform/`?

**Comment by physicien** [comment]
Hi, the exact past is `/sys/devices/platform/asus-nb-wmi/` for my configuration, so the second choice.

**Comment by flozz** [comment]
Ok, so what is the result of the following commands?

    find /sys/devices/platform/asus-nb-wmi/ -iname "*brightness*"
    find /sys/devices/platform/asus-nb-wmi/ -iname "*led*"

**Comment by physicien** [comment]
The first return nothing, but the second return 
`/sys/devices/platform/asus-nb-wmi/input/input10/capabilities/led`

**Comment by flozz** [comment]
Ok, so it seems your laptop is not supported by asus-nb-wmi module... I cannot do anything here (this project is just a glue between acpi hotkeys and the asus_laptop / asus-nb_wmi modules).

 You may want to report your issue upstream → https://bugzilla.kernel.org

Best regards

**Comment by physicien** [comment]
Thanks for your help, I think the solution is to [patch the kernel](https://bugzilla.kernel.org/show_bug.cgi?id=194557) (if anyone else have the same problem).

**Comment by flozz** [comment]
thank you for the information, I close this issue as it is not solvable in this repo :)
