### ISSUE TITLE
without root?

### ISSUE THREAD

**Issue by Soneji** [flozz/asus-keyboard-backlight#4]
I was hoping to implement this super useful utility in a script within awesome wm to control my keyboard brightness through the default brightness keys. Is there any way to make the script run without me having to type sudo before the command or run as root as awesome wm is not running as root. I am using arch linux and the latest version of asus-keyboard-backlight from the AUR

**Comment by flozz** [comment]
Hello,

There is several possibilities:

* ~~using the suid to make the script executed as root user~~ → this cannot be done on scripts (the suid must be set on the interpreter and this is a bad idea)
* finding a way to make the `/sys/devices/platform/asus_laptop/leds/asus::kbd_backlight/brightness` file writable by the desired user
* using `sudo` (it is possible to allow sudo to execute a specific command without password)
* ~~Implementing a daemon/client application~~ → a little bit overkill for what we are trying to achieve here :)

The best way for me is using sudo. you can configure it using the `visudo` command (as root) and adding the line that looks like this:

    username ALL(ALL:ALL) NOPASSWD: /path/to/the/script.py

:)

**Comment by Soneji** [comment]
{{Warning|The following way is not recommended. It provides world-writeable permissions to the keyboard backlight device file meaning that any and every user can control it.}}
The keyboard backlight file is usually locked out from editing. To unlock this file at bootup, you will need to create a [[systemd]] service.

{{hc|/usr/lib/systemd/system/asus-kbd-backlight.service|<nowiki>
[Unit]
Description=Asus Keyboard Backlight
Wants=systemd-backlight@leds:asus::kbd_backlight.service
After=systemd-backlight@leds:asus::kbd_backlight.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/chmod 666 /sys/class/leds/asus::kbd_backlight/brightness

[Install]
WantedBy=multi-user.target</nowiki>}}
You are now able to use a keyboard backlight changer script. For an example, see [[ASUS G55VW#keyboard backlight script]].

For an example of how you might set up a tiny daemon (running as root) that edits these files, hook it up to [[dbus]], and map the keyboard brightness keys to [[dbus]] method calls, see [https://github.com/GambolingPangolin/KbdBacklight].

from arch wiki
